name: Update Time Spent On Issues

on:
  issue_comment:
    types: [created, edited]

jobs:
  get-comments:
    if: ${{ startsWith(github.event.comment.body, '!spend') }}
    runs-on: ubuntu-latest
    outputs:
      comments: ${{ steps.generate-matrix.outputs.comments }}

    steps:
      - name: Time spent control
        uses: Libertech-FR/lt-actions/issue-spend@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
